### ISSUE TITLE
Some languages are not supported, e.g. Chinese Japanese

### ISSUE THREAD

**Issue by fishandsheep** [simonw/shot-scraper-template#7]
Hi:
As the title suggests，I'm not sure if this is an issue

for example this url:
```
https://zh.wikipedia.org/wiki/Ubuntu
```
I think it might be the ubuntu system of github action, I have no problem using shot-scraper directly from my local system.

If can't solve it, I will close this issue, thanks.

**Comment by simonw** [comment]
Yeah that's interesting - presumably this is because the fonts are missing?

https://unix.stackexchange.com/questions/39542/how-to-make-chinese-characters-display-properly-on-chromium suggests you might be able to add this to get them to work:

    sudo apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core

**Comment by simonw** [comment]
Adding that worked! https://github.com/simonw/shot-scraper-template-issue-7/commit/e4fbde0c18d923c67cab2c065cc160dcaceebd1a shows the difference

![Screenshot](https://github.com/simonw/shot-scraper-template-issue-7/blob/e4fbde0c18d923c67cab2c065cc160dcaceebd1a/shot.png?raw=true)

**Comment by simonw** [comment]
I don't want to add this line to the template because I worry about the extra download overhead of installing those fonts for users who don't need them. I'll add a note to the documentation instead.
